version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_TELEMETRY_DISABLED: 1
    env_file: .env
    volumes:
      - ./:/app:cached
      - next:/app/src/.next:delegated
      - node_modules:/app/node_modules:delegated
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    tty: true

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
volumes:
  next:
  node_modules: